/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_yythac_yftpserver_YFtpController */

#ifndef _Included_com_yythac_yftpserver_YFtpController
#define _Included_com_yythac_yftpserver_YFtpController

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_yythac_yftpserver_YFtpController_stringFromJNI( JNIEnv* env,
                                                  jobject thiz );
/*
 * Class:     com_yythac_yftpserver_YFtpController
 * Method:    StartFtpServer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_yythac_yftpserver_YFtpController_StartFtpServer
  (JNIEnv *, jobject);

/*
 * Class:     com_yythac_yftpserver_YFtpController
 * Method:    StopFtpServer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_yythac_yftpserver_YFtpController_StopFtpServer
  (JNIEnv *, jobject);

/*
 * Class:     com_yythac_yftpserver_YFtpController
 * Method:    SetListenPort
 * Signature: (I)Z
 */
//bool init_ftp_server(bool bDoAllow, const wchar_t *szusername,const wchar_t *szpassword
//		,const wchar_t *szStartPath, unsigned char ucPriv=FTP_USER_PRIV_READ,int port=2121);
JNIEXPORT jboolean JNICALL Java_com_yythac_yftpserver_YFtpController_InitFtpServer
  (JNIEnv *, jobject, jboolean bDoAllow,jstring szusername,jstring szpassword,jstring szStartPath,jbyte ucPriv,jint port);

#ifdef __cplusplus
}
#endif
#endif
